package quote

// DetectedEnemyAirArmyQuotes contains SCV-like quotes for when the bot detects
// an enemy air army unit.
var DetectedEnemyAirArmyQuotes = []string{
	"Air raid? More like air mistake!",
	"Air show's about to get explosive!",
	"Bet them flyers weren't cheap!",
	"Comin' right into our sights!",
	"Company policy: shoot down bogeys!",
	"Ever seen a turret volley?",
	"Fancy birds ya got there!",
	"Fancy meetin' y'all up there!",
	"Fly high, crash harder!",
	"Flyin' ain't gonna save ya!",
	"Got some nerve, don't ya?",
	"Gravity's on our side!",
	"Guess who's got turrets?",
	"Hope insurance covers missiles!",
	"Hope ya brought parachutes!",
	"Keep flyin', we'll keep shootin'!",
	"Mighty bold of ya there!",
	"Missiles lookin' for friends!",
	"Nice targets up there!",
	"Our turrets need practice!",
	"Our turrets were gettin' lonely!",
	"Pretty targets in the sky!",
	"Shoulda stayed grounded!",
	"That the best air force ya got?",
	"Them wings won't help ya!",
	"Them's thin-skinned flyers!",
	"This airshow's gettin' canceled!",
	"Those birds are in trouble!",
	"Turret crews needed some fun!",
	"We love flyin' target practice!",
	"We see ya up there!",
	"We shoot down uninvited guests!",
	"Welcome to missile country!",
	"Wrong airspace, buddy!",
	"Y'all call that flyin'?",
	"Y'all picked the wrong sky!",
}
