name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - run: go build

      - run: zip -9 "BlackCompany-$VERSION.zip" BlackCompany LICENSE.md README.md
        env:
          VERSION: ${{ github.ref_name }}

      - run: gh release create "$VERSION" --generate-notes --title "$VERSION" --verify-tag "BlackCompany-$VERSION.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
